services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgresql://user:password@db:5432/gapfinder
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "flask db init && flask db migrate -m 'Initial migration' && python init_db.py && flask run"
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gapfinder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gapfinder"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: